### ISSUE TITLE
Eng/Deu Bezeichnungen

### ISSUE THREAD

**Issue by mozita** [urbandwin/issues#15]
Auf eine Sprache einigen bezüglich der Suchfunktion. Bibliotheken findet man mit "libraries". Ich fände deutsch besser als erste Sprache. Alternativ so modeln, dass die Suche deutsch versteht und den englischen Kategorien/Bezeichnungen zuordnen kann.

Things along Kategorien sind auch mixed, teils auf eng. und teils deu.

**Comment by sebkur** [comment]
Inzwischen ist weitestgehend auf deutsch als Standardsprache umgestellt
