### ISSUE TITLE
Webseite in Simple info nicht angezeigt

### ISSUE THREAD

**Issue by mozita** [urbandwin/issues#2]
In OSM ist die Webseite angegeben, mit dem key contact:website:
https://urbandwin.com/openstreetmap/node/6004623953

In der Simple info taucht der Link zur Webseite nicht auf. Das ist bei mehreren Einträgen so.

Hier funktioniert es jedoch, mit dem key website:
https://urbandwin.com/openstreetmap/node/4821571805

Wäre gut, wenn beide Links in der Simple info funktionieren.

**Comment by sebkur** [comment]
Okay, läuft jetzt, siehe [hier](https://urbandwin.com/openstreetmap/simple/node/6004623953) und [hier](https://urbandwin.com/openstreetmap/simple/node/4821571805).
